using System;
using System.Collections.Generic;
using System.Linq;

namespace Kapa.Culture
{
    public static class Countries
    {
        #region Two letter country codes

        public const string AfghanistanTwoLetterCode = "AF";
        public const string AlandIslandsTwoLetterCode = "AX";
        public const string AlbaniaTwoLetterCode = "AL";
        public const string AlgeriaTwoLetterCode = "DZ";
        public const string AmericanSamoaTwoLetterCode = "AS";
        public const string AndorraTwoLetterCode = "AD";
        public const string AngolaTwoLetterCode = "AO";
        public const string AnguillaTwoLetterCode = "AI";
        public const string AntarcticaTwoLetterCode = "AQ";
        public const string AntiguaAndBarbudaTwoLetterCode = "AG";
        public const string ArgentinaTwoLetterCode = "AR";
        public const string ArmeniaTwoLetterCode = "AM";
        public const string ArubaTwoLetterCode = "AW";
        public const string AustraliaTwoLetterCode = "AU";
        public const string AustriaTwoLetterCode = "AT";
        public const string AzerbaijanTwoLetterCode = "AZ";
        public const string BahamasTwoLetterCode = "BS";
        public const string BahrainTwoLetterCode = "BH";
        public const string BangladeshTwoLetterCode = "BD";
        public const string BarbadosTwoLetterCode = "BB";
        public const string BelarusTwoLetterCode = "BY";
        public const string BelgiumTwoLetterCode = "BE";
        public const string BelizeTwoLetterCode = "BZ";
        public const string BeninTwoLetterCode = "BJ";
        public const string BermudaTwoLetterCode = "BM";
        public const string BhutanTwoLetterCode = "BT";
        public const string BoliviaTwoLetterCode = "BO";
        public const string CaribbeanNetherlandsTwoLetterCode = "BQ";
        public const string BosniaAndHerzegovinaTwoLetterCode = "BA";
        public const string BotswanaTwoLetterCode = "BW";
        public const string BouvetIslandTwoLetterCode = "BV";
        public const string BrazilTwoLetterCode = "BR";
        public const string BritishIndianOceanTerritoryTwoLetterCode = "IO";
        public const string BruneiDarussalamTwoLetterCode = "BN";
        public const string BulgariaTwoLetterCode = "BG";
        public const string BurkinaFasoTwoLetterCode = "BF";
        public const string BurundiTwoLetterCode = "BI";
        public const string CaboVerdeTwoLetterCode = "CV";
        public const string CambodiaTwoLetterCode = "KH";
        public const string CameroonTwoLetterCode = "CM";
        public const string CanadaTwoLetterCode = "CA";
        public const string CaymanIslandsTwoLetterCode = "KY";
        public const string CentralAfricanRepublicTwoLetterCode = "CF";
        public const string ChadTwoLetterCode = "TD";
        public const string ChileTwoLetterCode = "CL";
        public const string ChinaTwoLetterCode = "CN";
        public const string ChristmasIslandTwoLetterCode = "CX";
        public const string CocosKeelingIslandsTwoLetterCode = "CC";
        public const string ColombiaTwoLetterCode = "CO";
        public const string ComorosTwoLetterCode = "KM";
        public const string CongoDemocraticRepublicTwoLetterCode = "CD";
        public const string CongoTwoLetterCode = "CG";
        public const string CookIslandsTwoLetterCode = "CK";
        public const string CostaRicaTwoLetterCode = "CR";
        public const string CroatiaTwoLetterCode = "HR";
        public const string CubaTwoLetterCode = "CU";
        public const string CuracaoTwoLetterCode = "CW";
        public const string CyprusTwoLetterCode = "CY";
        public const string CzechiaTwoLetterCode = "CZ";
        public const string DenmarkTwoLetterCode = "DK";
        public const string DjiboutiTwoLetterCode = "DJ";
        public const string DominicaTwoLetterCode = "DM";
        public const string DominicanRepublicTwoLetterCode = "DO";
        public const string EcuadorTwoLetterCode = "EC";
        public const string EgyptTwoLetterCode = "EG";
        public const string ElSalvadorTwoLetterCode = "SV";
        public const string EquatorialGuineaTwoLetterCode = "GQ";
        public const string EritreaTwoLetterCode = "ER";
        public const string EstoniaTwoLetterCode = "EE";
        public const string EswatiniTwoLetterCode = "SZ";
        public const string EthiopiaTwoLetterCode = "ET";
        public const string FalklandIslandsTwoLetterCode = "FK";
        public const string FaroeIslandsTwoLetterCode = "FO";
        public const string FijiTwoLetterCode = "FJ";
        public const string FinlandTwoLetterCode = "FI";
        public const string FranceTwoLetterCode = "FR";
        public const string FrenchGuianaTwoLetterCode = "GF";
        public const string FrenchPolynesiaTwoLetterCode = "PF";
        public const string FrenchSouthernTerritoriesTwoLetterCode = "TF";
        public const string GabonTwoLetterCode = "GA";
        public const string GambiaTwoLetterCode = "GM";
        public const string GeorgiaTwoLetterCode = "GE";
        public const string GermanyTwoLetterCode = "DE";
        public const string GhanaTwoLetterCode = "GH";
        public const string GibraltarTwoLetterCode = "GI";
        public const string GreeceTwoLetterCode = "GR";
        public const string GreenlandTwoLetterCode = "GL";
        public const string GrenadaTwoLetterCode = "GD";
        public const string GuadeloupeTwoLetterCode = "GP";
        public const string GuamTwoLetterCode = "GU";
        public const string GuatemalaTwoLetterCode = "GT";
        public const string GuernseyTwoLetterCode = "GG";
        public const string GuineaTwoLetterCode = "GN";
        public const string GuineaBissauTwoLetterCode = "GW";
        public const string GuyanaTwoLetterCode = "GY";
        public const string HaitiTwoLetterCode = "HT";
        public const string HeardIslandAndMcDonaldIslandsTwoLetterCode = "HM";
        public const string HolySeeTwoLetterCode = "VA";
        public const string HondurasTwoLetterCode = "HN";
        public const string HongKongTwoLetterCode = "HK";
        public const string HungaryTwoLetterCode = "HU";
        public const string IcelandTwoLetterCode = "IS";
        public const string IndiaTwoLetterCode = "IN";
        public const string IndonesiaTwoLetterCode = "ID";
        public const string IranTwoLetterCode = "IR";
        public const string IraqTwoLetterCode = "IQ";
        public const string IrelandTwoLetterCode = "IE";
        public const string IsleofManTwoLetterCode = "IM";
        public const string IsraelTwoLetterCode = "IL";
        public const string ItalyTwoLetterCode = "IT";
        public const string IvoryCoastTwoLetterCode = "CI";
        public const string JamaicaTwoLetterCode = "JM";
        public const string JapanTwoLetterCode = "JP";
        public const string JerseyTwoLetterCode = "JE";
        public const string JordanTwoLetterCode = "JO";
        public const string KazakhstanTwoLetterCode = "KZ";
        public const string KenyaTwoLetterCode = "KE";
        public const string KiribatiTwoLetterCode = "KI";
        public const string KuwaitTwoLetterCode = "KW";
        public const string KyrgyzstanTwoLetterCode = "KG";
        public const string LaosTwoLetterCode = "LA";
        public const string LatviaTwoLetterCode = "LV";
        public const string LebanonTwoLetterCode = "LB";
        public const string LesothoTwoLetterCode = "LS";
        public const string LiberiaTwoLetterCode = "LR";
        public const string LibyaTwoLetterCode = "LY";
        public const string LiechtensteinTwoLetterCode = "LI";
        public const string LithuaniaTwoLetterCode = "LT";
        public const string LuxembourgTwoLetterCode = "LU";
        public const string MacaoTwoLetterCode = "MO";
        public const string MadagascarTwoLetterCode = "MG";
        public const string MalawiTwoLetterCode = "MW";
        public const string MalaysiaTwoLetterCode = "MY";
        public const string MaldivesTwoLetterCode = "MV";
        public const string MaliTwoLetterCode = "ML";
        public const string MaltaTwoLetterCode = "MT";
        public const string MarshallIslandsTwoLetterCode = "MH";
        public const string MartiniqueTwoLetterCode = "MQ";
        public const string MauritaniaTwoLetterCode = "MR";
        public const string MauritiusTwoLetterCode = "MU";
        public const string MayotteTwoLetterCode = "YT";
        public const string MexicoTwoLetterCode = "MX";
        public const string MicronesiaTwoLetterCode = "FM";
        public const string MoldovaTwoLetterCode = "MD";
        public const string MonacoTwoLetterCode = "MC";
        public const string MongoliaTwoLetterCode = "MN";
        public const string MontenegroTwoLetterCode = "ME";
        public const string MontserratTwoLetterCode = "MS";
        public const string MoroccoTwoLetterCode = "MA";
        public const string MozambiqueTwoLetterCode = "MZ";
        public const string MyanmarTwoLetterCode = "MM";
        public const string NamibiaTwoLetterCode = "NA";
        public const string NauruTwoLetterCode = "NR";
        public const string NepalTwoLetterCode = "NP";
        public const string NetherlandsTwoLetterCode = "NL";
        public const string NewCaledoniaTwoLetterCode = "NC";
        public const string NewZealandTwoLetterCode = "NZ";
        public const string NicaraguaTwoLetterCode = "NI";
        public const string NigerTwoLetterCode = "NE";
        public const string NigeriaTwoLetterCode = "NG";
        public const string NiueTwoLetterCode = "NU";
        public const string NorfolkIslandTwoLetterCode = "NF";
        public const string NorthernMarianaIslandsTwoLetterCode = "MP";
        public const string NorthKoreaTwoLetterCode = "KP";
        public const string NorwayTwoLetterCode = "NO";
        public const string OmanTwoLetterCode = "OM";
        public const string PakistanTwoLetterCode = "PK";
        public const string PalauTwoLetterCode = "PW";
        public const string PalestineTwoLetterCode = "PS";
        public const string PanamaTwoLetterCode = "PA";
        public const string PapuaNewGuineaTwoLetterCode = "PG";
        public const string ParaguayTwoLetterCode = "PY";
        public const string PeruTwoLetterCode = "PE";
        public const string PhilippinesTwoLetterCode = "PH";
        public const string PitcairnTwoLetterCode = "PN";
        public const string PolandTwoLetterCode = "PL";
        public const string PortugalTwoLetterCode = "PT";
        public const string PuertoRicoTwoLetterCode = "PR";
        public const string QatarTwoLetterCode = "QA";
        public const string NorthMacedoniaTwoLetterCode = "MK";
        public const string RomaniaTwoLetterCode = "RO";
        public const string RussiaTwoLetterCode = "RU";
        public const string RwandaTwoLetterCode = "RW";
        public const string ReunionTwoLetterCode = "RE";
        public const string SaintBarthelemyTwoLetterCode = "BL";
        public const string SaintHelenaAscensionAndTristanDaCunhaTwoLetterCode = "SH";
        public const string SaintKittsAndNevisTwoLetterCode = "KN";
        public const string SaintLuciaTwoLetterCode = "LC";
        public const string SaintMartinTwoLetterCode = "MF";
        public const string SaintPierreAndMiquelonTwoLetterCode = "PM";
        public const string SaintVincentAndTheGrenadinesTwoLetterCode = "VC";
        public const string SamoaTwoLetterCode = "WS";
        public const string SanMarinoTwoLetterCode = "SM";
        public const string SaoTomeAndPrincipeTwoLetterCode = "ST";
        public const string SaudiArabiaTwoLetterCode = "SA";
        public const string SenegalTwoLetterCode = "SN";
        public const string SerbiaTwoLetterCode = "RS";
        public const string SeychellesTwoLetterCode = "SC";
        public const string SierraLeoneTwoLetterCode = "SL";
        public const string SingaporeTwoLetterCode = "SG";
        public const string SintMaartenTwoLetterCode = "SX";
        public const string SlovakiaTwoLetterCode = "SK";
        public const string SloveniaTwoLetterCode = "SI";
        public const string SolomonIslandsTwoLetterCode = "SB";
        public const string SomaliaTwoLetterCode = "SO";
        public const string SouthAfricaTwoLetterCode = "ZA";
        public const string SouthGeorgiaAndTheSouthSandwichIslandsTwoLetterCode = "GS";
        public const string SouthKoreaTwoLetterCode = "KR";
        public const string SouthSudanTwoLetterCode = "SS";
        public const string SpainTwoLetterCode = "ES";
        public const string SriLankaTwoLetterCode = "LK";
        public const string SudanTwoLetterCode = "SD";
        public const string SurinameTwoLetterCode = "SR";
        public const string SvalbardAndJanMayenTwoLetterCode = "SJ";
        public const string SwedenTwoLetterCode = "SE";
        public const string SwitzerlandTwoLetterCode = "CH";
        public const string SyrianArabRepublicTwoLetterCode = "SY";
        public const string TaiwanTwoLetterCode = "TW";
        public const string TajikistanTwoLetterCode = "TJ";
        public const string TanzaniaTwoLetterCode = "TZ";
        public const string ThailandTwoLetterCode = "TH";
        public const string TimorLesteTwoLetterCode = "TL";
        public const string TogoTwoLetterCode = "TG";
        public const string TokelauTwoLetterCode = "TK";
        public const string TongaTwoLetterCode = "TO";
        public const string TrinidadAndTobagoTwoLetterCode = "TT";
        public const string TunisiaTwoLetterCode = "TN";
        public const string TurkeyTwoLetterCode = "TR";
        public const string TurkmenistanTwoLetterCode = "TM";
        public const string TurksAndCaicosIslandsTwoLetterCode = "TC";
        public const string TuvaluTwoLetterCode = "TV";
        public const string UgandaTwoLetterCode = "UG";
        public const string UkraineTwoLetterCode = "UA";
        public const string UnitedArabEmiratesTwoLetterCode = "AE";
        public const string UnitedKingdomTwoLetterCode = "GB";
        public const string UnitedStatesMinorOutlyingIslandsTwoLetterCode = "UM";
        public const string UnitedStatesOfAmericaTwoLetterCode = "US";
        public const string UruguayTwoLetterCode = "UY";
        public const string UzbekistanTwoLetterCode = "UZ";
        public const string VanuatuTwoLetterCode = "VU";
        public const string VenezuelaTwoLetterCode = "VE";
        public const string VietNamTwoLetterCode = "VN";
        public const string VirginIslandsBritishTwoLetterCode = "VG";
        public const string VirginIslandsUSTwoLetterCode = "VI";
        public const string WallisAndFutunaTwoLetterCode = "WF";
        public const string WesternSaharaTwoLetterCode = "EH";
        public const string YemenTwoLetterCode = "YE";
        public const string ZambiaTwoLetterCode = "ZM";
        public const string ZimbabweTwoLetterCode = "ZW";

        #endregion

        #region Three letter country codes

        public const string AfghanistanThreeLetterCode = "AFG";
        public const string AlandIslandsThreeLetterCode = "ALA";
        public const string AlbaniaThreeLetterCode = "ALB";
        public const string AlgeriaThreeLetterCode = "DZA";
        public const string AmericanSamoaThreeLetterCode = "ASM";
        public const string AndorraThreeLetterCode = "AND";
        public const string AngolaThreeLetterCode = "AGO";
        public const string AnguillaThreeLetterCode = "AIA";
        public const string AntarcticaThreeLetterCode = "ATA";
        public const string AntiguaAndBarbudaThreeLetterCode = "ATG";
        public const string ArgentinaThreeLetterCode = "ARG";
        public const string ArmeniaThreeLetterCode = "ARM";
        public const string ArubaThreeLetterCode = "ABW";
        public const string AustraliaThreeLetterCode = "AUS";
        public const string AustriaThreeLetterCode = "AUT";
        public const string AzerbaijanThreeLetterCode = "AZE";
        public const string BahamasThreeLetterCode = "BHS";
        public const string BahrainThreeLetterCode = "BHR";
        public const string BangladeshThreeLetterCode = "BGD";
        public const string BarbadosThreeLetterCode = "BRB";
        public const string BelarusThreeLetterCode = "BLR";
        public const string BelgiumThreeLetterCode = "BEL";
        public const string BelizeThreeLetterCode = "BLZ";
        public const string BeninThreeLetterCode = "BEN";
        public const string BermudaThreeLetterCode = "BMU";
        public const string BhutanThreeLetterCode = "BTN";
        public const string BoliviaThreeLetterCode = "BOL";
        public const string BosniaAndHerzegovinaThreeLetterCode = "BIH";
        public const string BotswanaThreeLetterCode = "BWA";
        public const string BouvetIslandThreeLetterCode = "BVT";
        public const string BrazilThreeLetterCode = "BRA";
        public const string BritishIndianOceanTerritoryThreeLetterCode = "IOT";
        public const string BruneiDarussalamThreeLetterCode = "BRN";
        public const string BulgariaThreeLetterCode = "BGR";
        public const string BurkinaFasoThreeLetterCode = "BFA";
        public const string BurundiThreeLetterCode = "BDI";
        public const string CaribbeanNetherlandsThreeLetterCode = "BES";
        public const string CaboVerdeThreeLetterCode = "CPV";
        public const string CambodiaThreeLetterCode = "KHM";
        public const string CameroonThreeLetterCode = "CMR";
        public const string CanadaThreeLetterCode = "CAN";
        public const string CaymanIslandsThreeLetterCode = "CYM";
        public const string CentralAfricanRepublicThreeLetterCode = "CAF";
        public const string ChadThreeLetterCode = "TCD";
        public const string ChileThreeLetterCode = "CHL";
        public const string ChinaThreeLetterCode = "CHN";
        public const string ChristmasIslandThreeLetterCode = "CXR";
        public const string CocosKeelingIslandsThreeLetterCode = "CCK";
        public const string ColombiaThreeLetterCode = "COL";
        public const string ComorosThreeLetterCode = "COM";
        public const string CongoDemocraticRepublicThreeLetterCode = "COD";
        public const string CongoThreeLetterCode = "COG";
        public const string CookIslandsThreeLetterCode = "COK";
        public const string CostaRicaThreeLetterCode = "CRI";
        public const string CroatiaThreeLetterCode = "HRV";
        public const string CubaThreeLetterCode = "CUB";
        public const string CuracaoThreeLetterCode = "CUW";
        public const string CyprusThreeLetterCode = "CYP";
        public const string CzechiaThreeLetterCode = "CZE";
        public const string DenmarkThreeLetterCode = "DNK";
        public const string DjiboutiThreeLetterCode = "DJI";
        public const string DominicaThreeLetterCode = "DMA";
        public const string DominicanRepublicThreeLetterCode = "DOM";
        public const string EcuadorThreeLetterCode = "ECU";
        public const string EgyptThreeLetterCode = "EGY";
        public const string ElSalvadorThreeLetterCode = "SLV";
        public const string EquatorialGuineaThreeLetterCode = "GNQ";
        public const string EritreaThreeLetterCode = "ERI";
        public const string EstoniaThreeLetterCode = "EST";
        public const string EswatiniThreeLetterCode = "SWZ";
        public const string EthiopiaThreeLetterCode = "ETH";
        public const string FalklandIslandsThreeLetterCode = "FLK";
        public const string FaroeIslandsThreeLetterCode = "FRO";
        public const string FijiThreeLetterCode = "FJI";
        public const string FinlandThreeLetterCode = "FIN";
        public const string FranceThreeLetterCode = "FRA";
        public const string FrenchGuianaThreeLetterCode = "GUF";
        public const string FrenchPolynesiaThreeLetterCode = "PYF";
        public const string FrenchSouthernTerritoriesThreeLetterCode = "ATF";
        public const string GabonThreeLetterCode = "GAB";
        public const string GambiaThreeLetterCode = "GMB";
        public const string GeorgiaThreeLetterCode = "GEO";
        public const string GermanyThreeLetterCode = "DEU";
        public const string GhanaThreeLetterCode = "GHA";
        public const string GibraltarThreeLetterCode = "GIB";
        public const string GreeceThreeLetterCode = "GRC";
        public const string GreenlandThreeLetterCode = "GRL";
        public const string GrenadaThreeLetterCode = "GRD";
        public const string GuadeloupeThreeLetterCode = "GLP";
        public const string GuamThreeLetterCode = "GUM";
        public const string GuatemalaThreeLetterCode = "GTM";
        public const string GuernseyThreeLetterCode = "GGY";
        public const string GuineaThreeLetterCode = "GIN";
        public const string GuineaBissauThreeLetterCode = "GNB";
        public const string GuyanaThreeLetterCode = "GUY";
        public const string HaitiThreeLetterCode = "HTI";
        public const string HeardIslandandMcDonaldIslandsThreeLetterCode = "HMD";
        public const string HolySeeThreeLetterCode = "VAT";
        public const string HondurasThreeLetterCode = "HND";
        public const string HongKongThreeLetterCode = "HKG";
        public const string HungaryThreeLetterCode = "HUN";
        public const string IcelandThreeLetterCode = "ISL";
        public const string IndiaThreeLetterCode = "IND";
        public const string IndonesiaThreeLetterCode = "IDN";
        public const string IranThreeLetterCode = "IRN";
        public const string IraqThreeLetterCode = "IRQ";
        public const string IrelandThreeLetterCode = "IRL";
        public const string IsleofManThreeLetterCode = "IMN";
        public const string IsraelThreeLetterCode = "ISR";
        public const string ItalyThreeLetterCode = "ITA";
        public const string IvoryCoastThreeLetterCode = "CIV";
        public const string JamaicaThreeLetterCode = "JAM";
        public const string JapanThreeLetterCode = "JPN";
        public const string JerseyThreeLetterCode = "JEY";
        public const string JordanThreeLetterCode = "JOR";
        public const string KazakhstanThreeLetterCode = "KAZ";
        public const string KenyaThreeLetterCode = "KEN";
        public const string KiribatiThreeLetterCode = "KIR";
        public const string KuwaitThreeLetterCode = "KWT";
        public const string KyrgyzstanThreeLetterCode = "KGZ";
        public const string LaosThreeLetterCode = "LAO";
        public const string LatviaThreeLetterCode = "LVA";
        public const string LebanonThreeLetterCode = "LBN";
        public const string LesothoThreeLetterCode = "LSO";
        public const string LiberiaThreeLetterCode = "LBR";
        public const string LibyaThreeLetterCode = "LBY";
        public const string LiechtensteinThreeLetterCode = "LIE";
        public const string LithuaniaThreeLetterCode = "LTU";
        public const string LuxembourgThreeLetterCode = "LUX";
        public const string MacaoThreeLetterCode = "MAC";
        public const string MadagascarThreeLetterCode = "MDG";
        public const string MalawiThreeLetterCode = "MWI";
        public const string MalaysiaThreeLetterCode = "MYS";
        public const string MaldivesThreeLetterCode = "MDV";
        public const string MaliThreeLetterCode = "MLI";
        public const string MaltaThreeLetterCode = "MLT";
        public const string MarshallIslandsThreeLetterCode = "MHL";
        public const string MartiniqueThreeLetterCode = "MTQ";
        public const string MauritaniaThreeLetterCode = "MRT";
        public const string MauritiusThreeLetterCode = "MUS";
        public const string MayotteThreeLetterCode = "MYT";
        public const string MexicoThreeLetterCode = "MEX";
        public const string MicronesiaThreeLetterCode = "FSM";
        public const string MoldovaThreeLetterCode = "MDA";
        public const string MonacoThreeLetterCode = "MCO";
        public const string MongoliaThreeLetterCode = "MNG";
        public const string MontenegroThreeLetterCode = "MNE";
        public const string MontserratThreeLetterCode = "MSR";
        public const string MoroccoThreeLetterCode = "MAR";
        public const string MozambiqueThreeLetterCode = "MOZ";
        public const string MyanmarThreeLetterCode = "MMR";
        public const string NamibiaThreeLetterCode = "NAM";
        public const string NauruThreeLetterCode = "NRU";
        public const string NepalThreeLetterCode = "NPL";
        public const string NetherlandsThreeLetterCode = "NLD";
        public const string NewCaledoniaThreeLetterCode = "NCL";
        public const string NewZealandThreeLetterCode = "NZL";
        public const string NicaraguaThreeLetterCode = "NIC";
        public const string NigerThreeLetterCode = "NER";
        public const string NigeriaThreeLetterCode = "NGA";
        public const string NiueThreeLetterCode = "NIU";
        public const string NorfolkIslandThreeLetterCode = "NFK";
        public const string NorthernMarianaIslandsThreeLetterCode = "MNP";
        public const string NorthKoreaThreeLetterCode = "PRK";
        public const string NorthMacedoniaThreeLetterCode = "MKD";
        public const string NorwayThreeLetterCode = "NOR";
        public const string OmanThreeLetterCode = "OMN";
        public const string PakistanThreeLetterCode = "PAK";
        public const string PalauThreeLetterCode = "PLW";
        public const string PalestineThreeLetterCode = "PSE";
        public const string PanamaThreeLetterCode = "PAN";
        public const string PapuaNewGuineaThreeLetterCode = "PNG";
        public const string ParaguayThreeLetterCode = "PRY";
        public const string PeruThreeLetterCode = "PER";
        public const string PhilippinesThreeLetterCode = "PHL";
        public const string PitcairnThreeLetterCode = "PCN";
        public const string PolandThreeLetterCode = "POL";
        public const string PortugalThreeLetterCode = "PRT";
        public const string PuertoRicoThreeLetterCode = "PRI";
        public const string QatarThreeLetterCode = "QAT";
        public const string RomaniaThreeLetterCode = "ROU";
        public const string RussiaThreeLetterCode = "RUS";
        public const string RwandaThreeLetterCode = "RWA";
        public const string ReunionThreeLetterCode = "REU";
        public const string SaintBarthelemyThreeLetterCode = "BLM";
        public const string SaintHelenaAscensionAndTristanDaCunhaThreeLetterCode = "SHN";
        public const string SaintKittsAndNevisThreeLetterCode = "KNA";
        public const string SaintLuciaThreeLetterCode = "LCA";
        public const string SaintMartinThreeLetterCode = "MAF";
        public const string SaintPierreAndMiquelonThreeLetterCode = "SPM";
        public const string SaintVincentAndTheGrenadinesThreeLetterCode = "VCT";
        public const string SamoaThreeLetterCode = "WSM";
        public const string SanMarinoThreeLetterCode = "SMR";
        public const string SaoTomeAndPrincipeThreeLetterCode = "STP";
        public const string SaudiArabiaThreeLetterCode = "SAU";
        public const string SenegalThreeLetterCode = "SEN";
        public const string SerbiaThreeLetterCode = "SRB";
        public const string SeychellesThreeLetterCode = "SYC";
        public const string SierraLeoneThreeLetterCode = "SLE";
        public const string SingaporeThreeLetterCode = "SGP";
        public const string SintMaartenThreeLetterCode = "SXM";
        public const string SlovakiaThreeLetterCode = "SVK";
        public const string SloveniaThreeLetterCode = "SVN";
        public const string SolomonIslandsThreeLetterCode = "SLB";
        public const string SomaliaThreeLetterCode = "SOM";
        public const string SouthAfricaThreeLetterCode = "ZAF";
        public const string SouthGeorgiaAndTheSouthSandwichIslandsThreeLetterCode = "SGS";
        public const string SouthKoreaThreeLetterCode = "KOR";
        public const string SouthSudanThreeLetterCode = "SSD";
        public const string SpainThreeLetterCode = "ESP";
        public const string SriLankaThreeLetterCode = "LKA";
        public const string SudanThreeLetterCode = "SDN";
        public const string SurinameThreeLetterCode = "SUR";
        public const string SvalbardAndJanMayenThreeLetterCode = "SJM";
        public const string SwedenThreeLetterCode = "SWE";
        public const string SwitzerlandThreeLetterCode = "CHE";
        public const string SyrianArabRepublicThreeLetterCode = "SYR";
        public const string TaiwanThreeLetterCode = "TWN";
        public const string TajikistanThreeLetterCode = "TJK";
        public const string TanzaniaThreeLetterCode = "TZA";
        public const string ThailandThreeLetterCode = "THA";
        public const string TimorLesteThreeLetterCode = "TLS";
        public const string TogoThreeLetterCode = "TGO";
        public const string TokelauThreeLetterCode = "TKL";
        public const string TongaThreeLetterCode = "TON";
        public const string TrinidadAndTobagoThreeLetterCode = "TTO";
        public const string TunisiaThreeLetterCode = "TUN";
        public const string TurkeyThreeLetterCode = "TUR";
        public const string TurkmenistanThreeLetterCode = "TKM";
        public const string TurksAndCaicosIslandsThreeLetterCode = "TCA";
        public const string TuvaluThreeLetterCode = "TUV";
        public const string UgandaThreeLetterCode = "UGA";
        public const string UkraineThreeLetterCode = "UKR";
        public const string UnitedArabEmiratesThreeLetterCode = "ARE";
        public const string UnitedKingdomThreeLetterCode = "GBR";
        public const string UnitedStatesMinorOutlyingIslandsThreeLetterCode = "UMI";
        public const string UnitedStatesOfAmericaThreeLetterCode = "USA";
        public const string UruguayThreeLetterCode = "URY";
        public const string UzbekistanThreeLetterCode = "UZB";
        public const string VanuatuThreeLetterCode = "VUT";
        public const string VenezuelaThreeLetterCode = "VEN";
        public const string VietNamThreeLetterCode = "VNM";
        public const string VirginIslandsBritishThreeLetterCode = "VGB";
        public const string VirginIslandsUSThreeLetterCode = "VIR";
        public const string WallisAndFutunaThreeLetterCode = "WLF";
        public const string WesternSaharaThreeLetterCode = "ESH";
        public const string YemenThreeLetterCode = "YEM";
        public const string ZambiaThreeLetterCode = "ZMB";
        public const string ZimbabweThreeLetterCode = "ZWE";

        #endregion

        #region Numeric country codes

        public const string AfghanistanNumericCode = "004";
        public const string AlandIslandsNumericCode = "248";
        public const string AlbaniaNumericCode = "008";
        public const string AlgeriaNumericCode = "012";
        public const string AmericanSamoaNumericCode = "016";
        public const string AndorraNumericCode = "020";
        public const string AngolaNumericCode = "024";
        public const string AnguillaNumericCode = "660";
        public const string AntarcticaNumericCode = "010";
        public const string AntiguaAndBarbudaNumericCode = "028";
        public const string ArgentinaNumericCode = "032";
        public const string ArmeniaNumericCode = "051";
        public const string ArubaNumericCode = "533";
        public const string AustraliaNumericCode = "036";
        public const string AustriaNumericCode = "040";
        public const string AzerbaijanNumericCode = "031";
        public const string BahamasNumericCode = "044";
        public const string BahrainNumericCode = "048";
        public const string BangladeshNumericCode = "050";
        public const string BarbadosNumericCode = "052";
        public const string BelarusNumericCode = "112";
        public const string BelgiumNumericCode = "056";
        public const string BelizeNumericCode = "084";
        public const string BeninNumericCode = "204";
        public const string BermudaNumericCode = "060";
        public const string BhutanNumericCode = "064";
        public const string BoliviaNumericCode = "068";
        public const string CaribbeanNetherlandsNumericCode = "535";
        public const string BosniaAndHerzegovinaNumericCode = "070";
        public const string BotswanaNumericCode = "072";
        public const string BouvetIslandNumericCode = "074";
        public const string BrazilNumericCode = "076";
        public const string BritishIndianOceanTerritoryNumericCode = "086";
        public const string BruneiDarussalamNumericCode = "096";
        public const string BulgariaNumericCode = "100";
        public const string BurkinaFasoNumericCode = "854";
        public const string BurundiNumericCode = "108";
        public const string CaboVerdeNumericCode = "132";
        public const string CambodiaNumericCode = "116";
        public const string CameroonNumericCode = "120";
        public const string CanadaNumericCode = "124";
        public const string CaymanIslandsNumericCode = "136";
        public const string CentralAfricanRepublicNumericCode = "140";
        public const string ChadNumericCode = "148";
        public const string ChileNumericCode = "152";
        public const string ChinaNumericCode = "156";
        public const string ChristmasIslandNumericCode = "162";
        public const string CocosKeelingIslandsNumericCode = "166";
        public const string ColombiaNumericCode = "170";
        public const string ComorosNumericCode = "174";
        public const string CongoDemocraticRepublicNumericCode = "180";
        public const string CongoNumericCode = "178";
        public const string CookIslandsNumericCode = "184";
        public const string CostaRicaNumericCode = "188";
        public const string CroatiaNumericCode = "191";
        public const string CubaNumericCode = "192";
        public const string CuracaoNumericCode = "531";
        public const string CyprusNumericCode = "196";
        public const string CzechiaNumericCode = "203";
        public const string DenmarkNumericCode = "208";
        public const string DjiboutiNumericCode = "262";
        public const string DominicaNumericCode = "212";
        public const string DominicanRepublicNumericCode = "214";
        public const string EcuadorNumericCode = "218";
        public const string EgyptNumericCode = "818";
        public const string ElSalvadorNumericCode = "222";
        public const string EquatorialGuineaNumericCode = "226";
        public const string EritreaNumericCode = "232";
        public const string EstoniaNumericCode = "233";
        public const string EswatiniNumericCode = "748";
        public const string EthiopiaNumericCode = "231";
        public const string FalklandIslandsNumericCode = "238";
        public const string FaroeIslandsNumericCode = "234";
        public const string FijiNumericCode = "242";
        public const string FinlandNumericCode = "246";
        public const string FranceNumericCode = "250";
        public const string FrenchGuianaNumericCode = "254";
        public const string FrenchPolynesiaNumericCode = "258";
        public const string FrenchSouthernTerritoriesNumericCode = "260";
        public const string GabonNumericCode = "266";
        public const string GambiaNumericCode = "270";
        public const string GeorgiaNumericCode = "268";
        public const string GermanyNumericCode = "276";
        public const string GhanaNumericCode = "288";
        public const string GibraltarNumericCode = "292";
        public const string GreeceNumericCode = "300";
        public const string GreenlandNumericCode = "304";
        public const string GrenadaNumericCode = "308";
        public const string GuadeloupeNumericCode = "312";
        public const string GuamNumericCode = "316";
        public const string GuatemalaNumericCode = "320";
        public const string GuernseyNumericCode = "831";
        public const string GuineaNumericCode = "324";
        public const string GuineaBissauNumericCode = "624";
        public const string GuyanaNumericCode = "328";
        public const string HaitiNumericCode = "332";
        public const string HeardIslandAndMcDonaldIslandsNumericCode = "334";
        public const string HolySeeNumericCode = "336";
        public const string HondurasNumericCode = "340";
        public const string HongKongNumericCode = "344";
        public const string HungaryNumericCode = "348";
        public const string IcelandNumericCode = "352";
        public const string IndiaNumericCode = "356";
        public const string IndonesiaNumericCode = "360";
        public const string IranNumericCode = "364";
        public const string IraqNumericCode = "368";
        public const string IrelandNumericCode = "372";
        public const string IsleofManNumericCode = "833";
        public const string IsraelNumericCode = "376";
        public const string ItalyNumericCode = "380";
        public const string IvoryCoastNumericCode = "384";
        public const string JamaicaNumericCode = "388";
        public const string JapanNumericCode = "392";
        public const string JerseyNumericCode = "832";
        public const string JordanNumericCode = "400";
        public const string KazakhstanNumericCode = "398";
        public const string KenyaNumericCode = "404";
        public const string KiribatiNumericCode = "296";
        public const string KuwaitNumericCode = "414";
        public const string KyrgyzstanNumericCode = "417";
        public const string LaosNumericCode = "418";
        public const string LatviaNumericCode = "428";
        public const string LebanonNumericCode = "422";
        public const string LesothoNumericCode = "426";
        public const string LiberiaNumericCode = "430";
        public const string LibyaNumericCode = "434";
        public const string LiechtensteinNumericCode = "438";
        public const string LithuaniaNumericCode = "440";
        public const string LuxembourgNumericCode = "442";
        public const string MacaoNumericCode = "446";
        public const string MadagascarNumericCode = "450";
        public const string MalawiNumericCode = "454";
        public const string MalaysiaNumericCode = "458";
        public const string MaldivesNumericCode = "462";
        public const string MaliNumericCode = "466";
        public const string MaltaNumericCode = "470";
        public const string MarshallIslandsNumericCode = "584";
        public const string MartiniqueNumericCode = "474";
        public const string MauritaniaNumericCode = "478";
        public const string MauritiusNumericCode = "480";
        public const string MayotteNumericCode = "175";
        public const string MexicoNumericCode = "484";
        public const string MicronesiaNumericCode = "583";
        public const string MoldovaNumericCode = "498";
        public const string MonacoNumericCode = "492";
        public const string MongoliaNumericCode = "496";
        public const string MontenegroNumericCode = "499";
        public const string MontserratNumericCode = "500";
        public const string MoroccoNumericCode = "504";
        public const string MozambiqueNumericCode = "508";
        public const string MyanmarNumericCode = "104";
        public const string NamibiaNumericCode = "516";
        public const string NauruNumericCode = "520";
        public const string NepalNumericCode = "524";
        public const string NetherlandsNumericCode = "528";
        public const string NewCaledoniaNumericCode = "540";
        public const string NewZealandNumericCode = "554";
        public const string NicaraguaNumericCode = "558";
        public const string NigerNumericCode = "562";
        public const string NigeriaNumericCode = "566";
        public const string NiueNumericCode = "570";
        public const string NorfolkIslandNumericCode = "574";
        public const string NorthernMarianaIslandsNumericCode = "580";
        public const string NorthKoreaNumericCode = "408";
        public const string NorthMacedoniaNumericCode = "807";
        public const string NorwayNumericCode = "578";
        public const string OmanNumericCode = "512";
        public const string PakistanNumericCode = "586";
        public const string PalauNumericCode = "585";
        public const string PalestineNumericCode = "275";
        public const string PanamaNumericCode = "591";
        public const string PapuaNewGuineaNumericCode = "598";
        public const string ParaguayNumericCode = "600";
        public const string PeruNumericCode = "604";
        public const string PhilippinesNumericCode = "608";
        public const string PitcairnNumericCode = "612";
        public const string PolandNumericCode = "616";
        public const string PortugalNumericCode = "620";
        public const string PuertoRicoNumericCode = "630";
        public const string QatarNumericCode = "634";
        public const string RomaniaNumericCode = "642";
        public const string RussiaNumericCode = "643";
        public const string RwandaNumericCode = "646";
        public const string ReunionNumericCode = "638";
        public const string SaintBarthelemyNumericCode = "652";
        public const string SaintHelenaAscensionAndTristanDaCunhaNumericCode = "654";
        public const string SaintKittsAndNevisNumericCode = "659";
        public const string SaintLuciaNumericCode = "662";
        public const string SaintMartinNumericCode = "663";
        public const string SaintPierreAndMiquelonNumericCode = "666";
        public const string SaintVincentAndTheGrenadinesNumericCode = "670";
        public const string SamoaNumericCode = "882";
        public const string SanMarinoNumericCode = "674";
        public const string SaoTomeAndPrincipeNumericCode = "678";
        public const string SaudiArabiaNumericCode = "682";
        public const string SenegalNumericCode = "686";
        public const string SerbiaNumericCode = "688";
        public const string SeychellesNumericCode = "690";
        public const string SierraLeoneNumericCode = "694";
        public const string SingaporeNumericCode = "702";
        public const string SintMaartenNumericCode = "534";
        public const string SlovakiaNumericCode = "703";
        public const string SloveniaNumericCode = "705";
        public const string SolomonIslandsNumericCode = "090";
        public const string SomaliaNumericCode = "706";
        public const string SouthAfricaNumericCode = "710";
        public const string SouthGeorgiaAndTheSouthSandwichIslandsNumericCode = "239";
        public const string SouthKoreaNumericCode = "410";
        public const string SouthSudanNumericCode = "728";
        public const string SpainNumericCode = "724";
        public const string SriLankaNumericCode = "144";
        public const string SudanNumericCode = "729";
        public const string SurinameNumericCode = "740";
        public const string SvalbardAndJanMayenNumericCode = "744";
        public const string SwedenNumericCode = "752";
        public const string SwitzerlandNumericCode = "756";
        public const string SyrianArabRepublicNumericCode = "760";
        public const string TaiwanNumericCode = "158";
        public const string TajikistanNumericCode = "762";
        public const string TanzaniaNumericCode = "834";
        public const string ThailandNumericCode = "764";
        public const string TimorLesteNumericCode = "626";
        public const string TogoNumericCode = "768";
        public const string TokelauNumericCode = "772";
        public const string TongaNumericCode = "776";
        public const string TrinidadAndTobagoNumericCode = "780";
        public const string TunisiaNumericCode = "788";
        public const string TurkeyNumericCode = "792";
        public const string TurkmenistanNumericCode = "795";
        public const string TurksAndCaicosIslandsNumericCode = "796";
        public const string TuvaluNumericCode = "798";
        public const string UgandaNumericCode = "800";
        public const string UkraineNumericCode = "804";
        public const string UnitedArabEmiratesNumericCode = "784";
        public const string UnitedKingdomNumericCode = "826";
        public const string UnitedStatesMinorOutlyingIslandsNumericCode = "581";
        public const string UnitedStatesOfAmericaNumericCode = "840";
        public const string UruguayNumericCode = "858";
        public const string UzbekistanNumericCode = "860";
        public const string VanuatuNumericCode = "548";
        public const string VenezuelaNumericCode = "862";
        public const string VietNamNumericCode = "704";
        public const string VirginIslandsBritishNumericCode = "092";
        public const string VirginIslandsUSNumericCode = "850";
        public const string WallisAndFutunaNumericCode = "876";
        public const string WesternSaharaNumericCode = "732";
        public const string YemenNumericCode = "887";
        public const string ZambiaNumericCode = "894";
        public const string ZimbabweNumericCode = "716";

        #endregion

        #region Collections

        private static IReadOnlyDictionary<string, string> _countriesThreeLetter =
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                {AfghanistanTwoLetterCode, AfghanistanThreeLetterCode},
                {AlandIslandsTwoLetterCode, AlandIslandsThreeLetterCode},
                {GreeceTwoLetterCode, GreeceThreeLetterCode}
            };

        private static IReadOnlyDictionary<string, string> _countriesNumeric =
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                {AfghanistanTwoLetterCode, AfghanistanNumericCode},
                {AlandIslandsTwoLetterCode, AlandIslandsNumericCode},
                {GreeceTwoLetterCode, GreeceNumericCode}
            };

        #endregion

        #region Methods

        public static string GetThreeLetterCodeFromTwoLetterCode(string code)
        {
            if (string.IsNullOrEmpty(code))
            {
                return default;
            }

            return _countriesThreeLetter.TryGetValue(code.Trim(), out var isoCode) ? isoCode : default;
        }

        public static string GetNumericCodeFromTwoLetterCode(string code)
        {
            if (string.IsNullOrEmpty(code))
            {
                return default;
            }

            return _countriesNumeric.TryGetValue(code.Trim(), out var numericCode) ? numericCode : default;
        }

        public static string GetTwoLetterCodeFromNumericCode(string numericCode)
        {
            if (string.IsNullOrWhiteSpace(numericCode))
            {
                return default;
            }

            return _countriesNumeric?.FirstOrDefault(x => x.Value == numericCode.Trim()).Key;
        }

        public static string GetTwoLetterCodeFromThreeLetterCode(string code)
        {
            if (string.IsNullOrWhiteSpace(code))
            {
                return default;
            }

            return _countriesThreeLetter?.FirstOrDefault(x => x.Value == code.Trim()).Key;
        }

        #endregion
    }
}